# fly.toml app configuration file generated for ict729 on 2024-05-03T15:41:36+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ict729'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  DB_URI = 'mongodb+srv://12203441:DrowRanger@acetutoring.ghaf7xq.mongodb.net/AceTutoringDB'